### ISSUE TITLE
회차 정보 조회 컴포넌트 생성

### ISSUE THREAD

**Issue by publdaze** [KEEPER31337/Game-Baseball#5]
## 📝 Description
<img width="200" alt="image" src="https://github.com/KEEPER31337/Game-Baseball/assets/78250089/e8b19a0d-9440-4334-9aa4-f9b357424af4">

- 사용자가 입력한 숫자와 결과를 보여주는 컴포넌트
- index : number (회차 차시)
   status : 'Ready' | 'Playing' | 'Finished' (상태)
   value : string (입력값)
   result : { ball : number, strike : number} (결과)
   props로 사용

## ✅ TODO

- [x] 컴포넌트 props 설정
- [x] ui 구성

**Comment by publdaze** [comment]
1. `number` prop의 경우 타입은 string으로 받아오면 어떨까요? 첫번째 입력하는 수가 0일 수도 있을 것 같네요!
2. `result`는 strink와 ball을 각각 받아올 지, 한 prop으로 같이 받아올 지, 같이 받아온다면 어떤 형태로 받아올 지에 대한 설명 추가되면 좋을 것 같습니다!

**Comment by jasper200207** [comment]
> 1. `number` prop의 경우 타입은 string으로 받아오면 어떨까요? 첫번째 입력하는 수가 0일 수도 있을 것 같네요!
> 2. `result`는 strink와 ball을 각각 받아올 지, 한 prop으로 같이 받아올 지, 같이 받아온다면 어떤 형태로 받아올 지에 대한 설명 추가되면 좋을 것 같습니다!

자료형 정보가 부족한거 같아서 정보 추가 했습니다! 추가로 result같은 경우는 쓰는 경우가 많을거 같은데 따로 객체를 만들어 두는거 어떤가요?

number는 사용자가 입력한 숫자라는 의미에서 number로 했는데 자료형 number와 겹치는거 같아서 value로 변경했습니다.

result의 경우에는 ball, strike가 각각 number로 들어가있는 객체를 사용하는게 좋아보입니다. 추가로 result같은 경우는 쓰는 경우가 많을거 같은데 따로 객체를 만들어 두는거 어떤가요?

**Comment by publdaze** [comment]
객체로 받아오는 거 너무 좋습니다! 👍👍
