### ISSUE TITLE
각 턴 모달 닫히는 시점에 카운트 다운 다시 시작하도록 처리

### ISSUE THREAD

**Issue by publdaze** [KEEPER31337/Game-Baseball#55]
## 📝 Description

설명을 작성하세요.

## ✅ TODO

- [ ] todo1
- [ ] todo2

**Comment by pipisebastian** [comment]
이건 해당 이슈처리되면서 같이 해결될 듯 합니다!
https://github.com/KEEPER31337/Game-Baseball/issues/51
